# NumPy- Numerical Python
<ul>
    <li>NumPy is a general purpose array-processing package.It provides a high-performance multidimensional arrayobject,and tools for working with these arrays.</li>
    <li>A powerful N-Dimensional array object.</li>
    <li>Sophisticated functions.</li>
    <li>Tools for integrating C/C++ and Fortran code.</li>
    <li>Useful Linear algebra,Fourier transform,and random number capabilities.</li>

## Single-Dimensional Numpy Array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


## Multi-Dimensional Array

In [3]:
a=np.array(([1,2,3],[4,5,6]))
print(a)

[[1 2 3]
 [4 5 6]]


# Numpy array Vs Python List
<ul>
    <li>Less Memory</li>
    <li>Fast</li>
    <li>Convinient</li>
</ul>

In [7]:
#comparing memory occupied by both
import numpy as np
import sys
#memory occupied by list
s = range(1000)
print('memory occupied by List',sys.getsizeof(10)*len(s))
#memory occupied by numpy
d = np.arange(1000)
print('memory occupied by Numpy Array',d.size*d.itemsize)

memory occupied by List 28000
memory occupied by Numpy Array 4000


In [8]:
#comparing speed of list and numpy array
import time
size = 10000000
#checking list taken time
l1 = range(size)
l2 = range(size)
start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print('Time taken by List:', time.time()-start)
#checking numpy array taken time
a1 = np.arange(size)
a2 = np.arange(size)
start2 = time.time()
result_numpy = a1+a2
print('Time taken by numpy:', time.time()-start2)

Time taken by List: 139.11676454544067
Time taken by numpy: 0.232893705368042


In [9]:
import time
print(time.time())

1594636698.525628


# Np.arrange

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.arange(1,8,3)

array([1, 4, 7])

In [12]:
np.arange(1,10.1,3)

array([ 1.,  4.,  7., 10.])

In [13]:
np.arange(7,0,-3)

array([7, 4, 1])

In [14]:
x=np.arange(5)
print(x)
print(x.dtype)
print(x.itemsize)

[0 1 2 3 4]
int32
4


In [15]:
x=np.arange(5 , dtype=float)
print(x)
print(x.dtype)
print(x.itemsize)

[0. 1. 2. 3. 4.]
float64
8


In [16]:
x=np.arange(1,5.0,0.25)
print(x)
print(x.dtype)
print(x.itemsize)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75]
float64
8


#  Empty Array
If you provide equal values to start and stop then you will get empty aaray.

In [20]:
x=np.arange(0)
print(x)

[]


In [21]:
x=np.arange(2,2)
print(x)

[]


In [22]:
x=np.arange(8,2,1)
print(x)

[]


In [23]:
x=np.arange(2,8,-1)
print(x)

[]


# n.dim
It gives the dimention of the array.

In [24]:
a = np.array([(1,2,3),(4,5,6)])
a1 = np.array([((1,2,3),(4,5,6)),((1,2,3),(4,5,6))])
print(a.ndim)
print(a1.ndim)

2
3


# n.itemsize
Calculate the byte size of each element

In [27]:
import numpy as np
a = np.array([(1,2,3)])
print(a.itemsize)

4


# n.dtype
Find the data type of the elements that are stored in anarray.So,if you want to know the data type of a particular element, you can use‘dtype’ function which will print the datatypealong with the size.

In [28]:
a = np.array([(1,2,3)])
print(a.dtype)

int32


# Size and Shape
Find the size and shape of the array using ‘size’ and ‘shape’ function respectively.

In [29]:
a = np.array([(1,2,3,4,5,6)])
a1 = np.array([(1,2,3,3),(4,5,6,4)])
print(a1)
print(a1.size)
print(a1.shape)

[[1 2 3 3]
 [4 5 6 4]]
8
(2, 4)


# Reshape
Reshape is when you change the number of rows and columns which gives a new shape to the array.

In [33]:
a = np.array([(8,9,10),(11,12,13)])
print(a)
b = a.reshape(3,2)
print(b)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


# Slicing
Slicing is basically extracting particular set of elements from an array.

In [36]:
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[0,2])

[[1 2 3 4]
 [3 4 5 6]]
3


In [40]:
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])

[ 9 11]


# Linspace
Returns evenly spaced numbers over a specified interval.

In [42]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


# Max/Min & Sum

In [47]:
a=np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [48]:
a=np.array([(1,2,3),(4,5,6)])
print(a.min())
print(a.max())
print(a.sum())

1
6
21


In [54]:
a=np.array([(1,2,3),(3,4,5)])
print(a)
print("Sum of rows = ",a.sum(axis=1))
print("Sumof columns = ",a.sum(axis=0))

[[1 2 3]
 [3 4 5]]
Sum of rows =  [ 6 12]
Sumof columns =  [4 6 8]


# Square Root & Standard Deviation
How much each element varies from the mean value of the python numpy array.

In [56]:
a = np.array([(1,2,3),(3,4,5)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


# Mathematical Operations

In [57]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Vertical and Horizontal Stacking
If we want to concatenate two array and not just add them,we can perform it by two ways - Vertical Stacking and Horizontal Stacking.

In [58]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [59]:
a1 = np.arange(1,13)
a2 = np.arange(13,25)
print(np.stack((a1,a2)))
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))
print(np.stack((a1,a2), axis = 1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]
 [12 24]]


# Ravel
Convert one numpy array into single column i.e., ravel.

In [60]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]
